"""
Google OAuth verification route.

The frontend sends the Google Identity Services id_token as `credential`.
This backend verifies the token signature and audience with Google,
stores profile data in Postgres, and sets an httpOnly JWT cookie.
"""

from fastapi import APIRouter, HTTPException, Response, status
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token
from pydantic import BaseModel, Field

from app.config import settings
from app.core.security import create_access_token, set_auth_cookie, clear_auth_cookie
from app.core.dependencies import get_current_user
from app.core.rate_limit import limiter
from app.db.postgres import upsert_user_data
from app.utils.email import send_welcome_email
from app.utils.logger import logger
from fastapi import Depends, Request

router = APIRouter(prefix="/auth", tags=["Auth"])


class GoogleAuthRequest(BaseModel):
    """Request body for POST /auth/google."""

    credential: str | None = Field(default=None, description="Google id_token JWT")
    token: str | None = Field(default=None, description="Legacy alias for credential")
    state: str | None = Field(
        default=None,
        min_length=16,
        description="OAuth state/nonce generated by the frontend",
    )


class GoogleUserResponse(BaseModel):
    openid: str
    name: str | None = None
    email: str
    profile_url: str | None = None


class GoogleAuthResponse(BaseModel):
    status: str
    user: GoogleUserResponse


@router.post("/google", response_model=GoogleAuthResponse)
@limiter.limit("10/minute")
async def google_auth(request: Request, body: GoogleAuthRequest, response: Response):
    credential = body.credential or body.token
    if not credential:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="credential is required",
        )

    if not settings.google_client_id:
        logger.error("GOOGLE_CLIENT_ID is not configured on the server")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="OAuth is not configured",
        )

    try:
        idinfo = id_token.verify_oauth2_token(
            credential,
            google_requests.Request(),
            settings.google_client_id,
        )
    except ValueError as exc:
        logger.warning(f"Rejected invalid Google id_token: {exc}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Google token",
        ) from exc

    issuer = idinfo.get("iss")
    if issuer not in {"accounts.google.com", "https://accounts.google.com"}:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid Google token issuer",
        )

    if body.state and idinfo.get("nonce") != body.state:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid OAuth state",
        )

    openid = idinfo.get("sub")
    email = idinfo.get("email")
    if not openid or not email:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Google token is missing required identity fields",
        )

    if idinfo.get("email_verified") is False:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Google email address is not verified",
        )

    user = upsert_user_data(
        openid=openid,
        name=idinfo.get("name"),
        email=email,
        profile_url=idinfo.get("picture"),
    )

    # ── Send welcome email on every Google sign-in ───────
    send_welcome_email(to_email=email, user_name=idinfo.get("name"))

    # ── Create JWT and set httpOnly cookie ────────────────
    access_token = create_access_token(
        subject=openid,
        extra_claims={"email": email, "name": idinfo.get("name"), "profile_url": idinfo.get("picture")},
    )
    set_auth_cookie(response, access_token)
    logger.info(f"Auth success: set httpOnly cookie for user {email}")

    # Strip internal flag before returning to client
    user.pop("is_new_user", None)
    return {"status": "success", "user": user}


@router.post("/logout")
@limiter.limit("10/minute")
async def logout(request: Request, response: Response):
    """Clear the auth cookie to log the user out."""
    clear_auth_cookie(response)
    return {"status": "logged_out"}


@router.get("/me")
@limiter.limit("30/minute")
async def get_me(request: Request, user: dict = Depends(get_current_user)):
    """Return the current authenticated user's info from the JWT."""
    return {
        "openid": user.get("sub"),
        "email": user.get("email"),
        "name": user.get("name"),
        "profile_url": user.get("profile_url"),
    }
